# Generated by Django 4.0.5 on 2022-06-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiPrimerProyectoApp', '0005_rename_familiares_familiar_delete_estudiantes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
